# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing yarn
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install --production
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
      - yarn test
      - echo Creating bundle
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '*'
  base-directory: packages/frontend/dist
  discard-paths: yes
