
/* This file is generated by the flag editor util. Changes will be lost! */

export type Features = {
    CREATE_USN_CONTRACT: boolean;
	DONATE_TO_UKRAINE: boolean;
	EXAMPLE_FLAG: boolean;
	IMPORT_ZERO_BALANCE_ACCOUNT: boolean;
};
