
/* This file is generated by the flag editor util. Changes will be lost! */

export type Features = {
    CREATE_USN_CONTRACT: boolean;
	DONATE_TO_UKRAINE: boolean;
	FT_TRANSFER_REGISTRATION: boolean;
	HAPI_RISK_SCORING: boolean;
	RENDER_MIGRATION: boolean;
	SHOW_MIGRATION_BANNER: boolean;
	WEB3AUTH: boolean;
	WEP_PHASE_ONE: boolean;
};
