#!/usr/bin/env python
import argparse


def generate_config(out_file, nearlib_url):
    config = """near:
  nearlib_url: {}\n""".format(nearlib_url)
    with open(out_file, 'w') as f:
        f.write(config)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', required=True, type=str)
    parser.add_argument('--nearlib-url', required=True, type=str)
    args = parser.parse_args()
    generate_config(args.out, args.nearlib_url)
