name: Test Frontend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      near_wallet_env:
        required: true
        type: string

jobs:
  bundle-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/frontend
    env:
      NEAR_WALLET_ENV: ${{ inputs.near_wallet_env }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn bundle --outDir=dist/${{ inputs.environment }}
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-bundle
          path: packages/frontend/dist/${{ inputs.environment }}
