name: Test Frontend
on:
  pull_request:
jobs:
  bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/frontend
    env:
      NEAR_WALLET_ENV: testnet
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn bundle

  deploy:
    needs: bundle
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: packages/frontend
    steps:
      - uses: actions/checkout@master
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
        run: aws s3 sync dist/* s3://mnw-pr-previews
